### ISSUE TITLE
Users should be able to change their own posts.

### ISSUE THREAD

**Issue by eichie** [Yosimitso/WorkingForumBundle#18]
It would be nice if users should be able to change their own posts.

**Comment by Yosimitso** [comment]
Yes it would be cool, but we need to think about the quoting system for this feature because quotes into posts shouldn't change if the post is edited

**Comment by Clowrid** [comment]
This feature will quickly become essential.
In my opinion, you are right : If the author completely changes his message, then the response of the person who used the quote may seem totally off. Quotes shoudn't be updated.

**Comment by Yosimitso** [comment]
I agree we have to find a solution, because the quoting system works with the post.id quoted
I think adding a 'editedContent' in post entity to keep the original message

**Comment by Clowrid** [comment]
As part of my use, quotes are used very little. So I overrided the bundle to add the ability to edit own posts (or all posts for administrators). I can improve it a little and propose a pull request, but it will not settle the quote issue. In my opinion, instead of pointing to the original message,  quotes should simply copy the text. What do you think about this ? It seems to me that this is how it works on most forums.

**Comment by Yosimitso** [comment]
I don't wanna lose the perk of a database without html, and with the current system the rendering of quotes can be modified, so I don't think that the hard copy is a good idea.
 I think that adding a column won't slow down the forum and it's pretty easy, i'll think about it but I'm gonna take a look at your work ;)

**Comment by Clowrid** [comment]
Rather than storing html in a database (which it would be best to avoid i agree), can we store the mardown directly? 
Adding a column won't impact performance and this workdaround may work for one update, but what about few of them ? If a user regularly updates a topic (eg a topic that would list the movies releases of this year with an associated rating), how to update the quote ?

**Comment by Yosimitso** [comment]
quotes uses the post.id and they are rendered at display, so there're no need to update them if the quoted message has changed (or I didn't understand your question). I would keep only the original message and modified message without history because I think posts content shouldn't be modified after a while.
And yes storing markdown can be a solution too !

**Comment by Clowrid** [comment]
No worries, I wasn't necessarily very clear. I will take time to develop.
We must take into account two cases :
 
There is of course the case where an user want to change the content of his post just after writing it, usually to correct a typo. In this case, your solution is good. However, one might wonder if an user would have had time to quote this post  in the meantime


But there are also cases where some topics will evolve, especially the pinned topics. I will take another example: on a website that offers to read poems, we can imagine a pinned topic "best poems of the month" which displays the three best poems of the month. People could then use the quotes to comment and give their opinions. The next month (and every next months), the topic's author will change the topic's content to include the new poems. In this case, your solution won't work. This is only an example, but this kind of use is quite common (at least on the forums I read / moderates)

That's why I think that copying the markdown into the database is a better solution. This would also allow to quote only part of a post. This unfortunately has the disadvantage of making the quote editable
but that does not seem very annoying to me.

**Comment by Yosimitso** [comment]
Ah you're right Ii understand now :D but we can't make quote editable !
 maybe we can use a post history and use it in the tag, like [quote=1234 rev=2] (+ part of the text ?).
If we post directly markdown I don't see how to prevent the quotes edition

**Comment by Clowrid** [comment]
Personally, I think that keeping an history only in order to prevent quote edition is a bit too much. As I said, I don't really care about quote edition and a fair number of forum doesn't check quote integrity.

Now, if you really want to avoid quote edition, then you can actually do that, it's a solution :)
