### ISSUE TITLE
I can't install through setup file.

### ISSUE THREAD

**Issue by jhzao82** [Yosimitso/WorkingForumBundle#60]
I got this error Could not open input file: bin/console, After I run composer require and composer update.

**Comment by Yosimitso** [comment]
If you're using older version of symfony the path is app/console

**Comment by jhzao82** [comment]
I use both version 4 and 3, Maybe I not know how to install bundle, I have install symfony site before.

**Comment by Yosimitso** [comment]
What's the command after 'bin/console' ?
And check your composer.json in 'scripts' section, perhaps you have some wrong path to the 'console' executable
It could happen when you upgrade Symfony but not the directory structure, because on SF2 the 'console' executable was located in 'app/' and now it's located in 'bin/'
