### ISSUE TITLE
no profilertoolbar

### ISSUE THREAD

**Issue by wetternest** [Yosimitso/WorkingForumBundle#9]
as Common:base.html.twig does not extend ::base.html.twig there is no profilertoolbar

**Comment by Yosimitso** [comment]
That makes no sense, this bundle's view was created to be overridden in your application (app\Resources\YosimitsoWorkingForumBundle\views\Common\base.html.twig) ! The app doesn't have necessarily a file named ::base.html.twig, it depends on your application.

Example of  app\Resources\YosimitsoWorkingForumBundle\views\Common\base.html.twig in the demo :
`<html>
    <head>
 {% block stylesheets %}
    <link href="{{ asset('bundles/app/css/demo.css') }}" type="text/css" rel="stylesheet" />
{% endblock %}
<title>Demo of YosimitsoWorkingForumBundle</title> 
    </head>
    <body>
        <p>Demo of YosimitsoWorkingForumBundle - <a href="https://github.com/Yosimitso/WorkingForumBundle">https://github.com/Yosimitso/WorkingForumBundle</a></p>
        <p>Symfony 3.0.5 - Latest version of YosimitsoWorkingForumBundle</p>
{% block forum %}
{% endblock %}    
    </body>
</html>
`

**Comment by wetternest** [comment]
just for testing and developing it would be fine...
its just 3 lines that need to be added to Common:base.html.twig, so not a big deal ;-)
have a look at my pull-request, i already did the necessary changes!

**Comment by Yosimitso** [comment]
I think you don't get it, the bundle must be independent but adapt to every application with parameters, so you just have to override the Common:base.html.twig with the 3 lines you need.
Sorry but i can't integrate your work because I have already commit these changes (bugs and others), but I won't make modifications for a couple of days so if you have new interesting pull requests I'll merge your work ;)

**Comment by wetternest** [comment]
I'm sorry I hadn't had any time last weekend to merge your latest changes into my fork and make a pull request. But I'm working on it, perhaps I will find time to do this next week!
